assignment_config:
  language_model_list:
  - name: deepseek-chat
    custom_parameters:
      model_name: "deepseek-chat"
      api_key: "sk-d4226415d55d492fb913479f1a8b6b9c"
      base_url: "https://api.deepseek.com"
      role_dict:
        user: "user"
        agent: "assistant"
  agent:
    name: language_model_agent
    custom_parameters:
      language_model: deepseek-chat
      system_prompt: ""  # Empty system prompt - will use chat history
      inference_config_dict:
        temperature: 0.1
        max_tokens: 1000
